const caseStudies = [
  {
    slug: "superhuman-zero-to-one",
    tag: "zero to one",
    color: "accent",
    domain: "productivity / email",
    title: "Superhuman's invite only v1",
    hook: "scoping a v1 product around a 30 minute onboarding call instead of a feature list, and what that bought them.",
    sections: [
      { heading: "the problem", body: "By 2017 every email client looked basically the same. Fast enough inbox, search that mostly worked, and a long list of power user complaints nobody had bothered to fix in years. That kind of market usually scares a PM off. Superhuman's team treated it as the opening. Their read was that \"fast enough\" wasn't actually good enough for the people who live in their inbox all day, and that group was small enough to find and charge for directly." },
      { heading: "how I'd frame the bet", body: "Most early products try to get wide adoption first and clean up quality later. This one flipped that order. If your entire pitch is speed and polish, a so-so first impression kills word of mouth before it even starts. And word of mouth was the only channel that made sense for a $30 a month email app with no network effect to lean on." },
      { heading: "what they actually shipped", body: "The v1 product was narrow on purpose. Fast keyboard navigation, a split inbox, snippets, scheduled send, and not much beyond that. The part that made this a real zero to one story wasn't the feature list though, it was onboarding. Every new user got a 30 minute call with an actual human before they got access. That's a strange cost to pay for a product that's \"just email.\" It was the point. The call let the team watch in real time where people got confused or delighted, then fix it before the next batch of invites went out.\n\nAccess stayed invite only well past the point where it could've opened up. That wasn't only hype. Keeping cohorts small meant someone could actually sit with the feedback from every single onboarding call instead of drowning in it." },
      { heading: "what I'd push back on", body: "The onboarding call model doesn't scale and to their credit the team seemed to know that going in. What I'd flag with hindsight is who they were calibrating to. People willing to sit through a 30 minute call and pay $30 a month for email skew toward a pretty specific type of person, mostly ex Big Tech, ops and sales heavy roles. Tuning a roadmap tightly to that group for two years risks blind spots about how anyone else would actually use the thing. I'd have pushed to sample a wider set of invitees earlier even if it made the feedback noisier, so v2 wasn't just \"what our loudest users asked for twice.\"" },
      { heading: "the short version", body: "When speed and polish are the whole pitch, the real bottleneck is catching every bad first impression before it turns into a bad review. Scarcity is only worth it if it's buying you a tighter feedback loop, not just buzz." }
    ]
  },
  {
    slug: "linear-command-palette",
    tag: "teardown",
    color: "success",
    domain: "developer tools / project management",
    title: "Linear's command palette",
    hook: "reverse engineering the tradeoffs behind a keyboard first product, and what they refused to build around it.",
    sections: [
      { heading: "the problem", body: "Most project management tools force a constant context switch. You're typing a ticket, then you reach for the mouse to change its status, assign it, set a priority. Each switch is small but they add up, and for an engineer who lives in a keyboard driven editor all day, a tool that keeps making them grab the mouse feels slow no matter how fast its pages load." },
      { heading: "how I'd frame the bet", body: "Linear's bet is that the real unit of speed isn't page load time, it's keystrokes to outcome. Cmd+K isn't a bonus feature bolted onto the product, it's treated as the main way to do almost anything. Create an issue, change its state, jump to a project, search across the workspace, even change a setting. The mouse paths still exist but the whole product is built so the palette is never the slower option." },
      { heading: "what they actually shipped", body: "The mechanics by themselves are nothing special. Fuzzy search, recent items weighted higher, actions that change based on what's selected. What's interesting is what they didn't build around it. No deep settings menu with five levels of nesting, no sprawling sidebar with a view for everything. They kept the surface area narrow on purpose, because every extra navigation path is one more thing the palette's search has to compete against. A command palette is only as good as the worst case of \"I forgot what this is called,\" and that worst case gets worse every time you bolt on a feature that needs its own home in the nav.\n\nThe palette also leans on consistent naming across the whole product. The same action reads the same whether you trigger it from the palette, a shortcut, or a right click menu. You don't notice how much that matters until you imagine fuzzy search trying to work when the same action has three different names in three different places." },
      { heading: "what I'd push back on", body: "This works because Linear is a single purpose tool for a technically fluent audience. I don't think the same approach holds up for a less technical audience where the palette is competing against a mouse first mental model that's already fully formed, like a sales rep using a CRM who was never trained to think in commands. If I were advising a team copying this pattern, I'd want palette usage instrumented and broken out by user type early, instead of assuming it'll generalize. Linear's userbase basically self selected for it already." },
      { heading: "the short version", body: "The palette isn't the speed feature, it's the thing that kept the rest of the product from sprawling. Judge a command palette by what the team refused to build around it, not by the search algorithm." }
    ]
  },
  {
    slug: "stripe-checkout-redesign",
    tag: "redesign",
    color: "warning",
    domain: "payments / fintech",
    title: "Stripe Checkout",
    hook: "the unglamorous decisions, error copy and field order, that move a real completion rate.",
    sections: [
      { heading: "the problem", body: "Checkout is the least exciting screen in any product and the most expensive one to get wrong. Every extra field, every confusing error, every retry that silently fails costs real money at the exact moment someone already decided to pay you. Checkout abandonment is one of the few metrics where it's almost entirely your own fault." },
      { heading: "how I'd frame the bet", body: "Stripe's checkout product treats the boring stuff as the actual product. Card formatting, inline validation, autofill, local payment methods, none of that shows up in a pitch deck but it's the whole reason a merchant pays Stripe instead of building this themselves. The clearest tell is where they put their effort: error states. A declined card isn't an edge case to handle later, the messaging is specific enough to tell someone whether to retry, try a different card, or call their bank. A generic \"payment failed\" is where most homegrown checkout flows quietly lose a sale a slightly better message would've saved." },
      { heading: "what they actually shipped", body: "Link, Stripe's one click checkout for returning customers, is the clearest example of this thinking. Instead of leaving every merchant to solve \"returning customer doesn't want to re enter their card\" on their own, Stripe built it once across the network. The more merchants use it, the more often a shopper already has it set up, the faster checkout gets for everyone. That's a flywheel decision, not a UI decision. The bet was that solving the friction once, centrally, beats every merchant solving it slightly differently and slightly worse.\n\nThe quieter decision is in field order. Address fields don't all show up before payment method, and fields like \"billing matches shipping\" are collapsed by default. None of this looks like a feature, it just shows up as a slightly higher completion rate, which is the whole point. Nobody screenshots a checkout flow and says look how good this field order is." },
      { heading: "what I'd push back on", body: "The Link flywheel depends on enough merchants actually adopting it, which means early adopters are subsidizing an experience that gets better mostly for everyone who comes after them. If I were pitching a merchant on adopting this early, I'd want a clearer answer than \"trust us, it compounds\" for why it's worth it before the network effect has kicked in." },
      { heading: "the short version", body: "The most valuable work on checkout is invisible by design. Better error copy and smarter field order won't make a highlight reel but they're the actual lever on completion rate. Don't mistake boring for low leverage." }
    ]
  },
  {
    slug: "slack-threads-rollout",
    tag: "go to market",
    color: "danger",
    domain: "workplace communication / chat",
    title: "Slack's rollout of Threads",
    hook: "sequencing a risky change to a years old default without breaking the trust of people who use it out of habit.",
    sections: [
      { heading: "the problem", body: "Slack's core interaction is a flat scrolling channel, which works fine for fast back and forth but breaks down for any conversation that needs to branch off, a side discussion, a tangent, a decision that deserves its own context. Slack had threading for years but it was widely seen as confusing and underused. A 2023 redesign tried to make threading the default way conversations branch, with a dedicated Threads view. That's a much riskier rollout than it sounds, because it touches the muscle memory of a tool millions of people use every day without thinking about it." },
      { heading: "how I'd frame the bet", body: "Changing the default behavior of a tool people use out of habit is exactly the situation where a bad rollout does lasting damage. People don't evaluate a familiar tool's new defaults rationally, they react to the disruption first. The technically easier path, flip a flag for everyone at once, is actually the riskier path for trust. Slack instead leaned on phasing the change in gradually and keeping the old behavior reachable for a while, instead of forcing everyone onto the new thing on day one with no way back." },
      { heading: "what they actually shipped", body: "The redesigned Threads view pulled all of a user's threaded replies into one searchable place instead of leaving them scattered across channels where they were easy to lose. The change came with in product explanation of why, not just a changelog entry, which matters more for a habitual tool than for a brand new feature, because people need a reason to put up with a disruption they didn't ask for.\n\nThe rollout also accepted slower adoption in exchange for a smaller blast radius. Instead of calling it done at launch, the real test happened in the weeks after, watching for the signals that matter when you've changed muscle memory, like engagement dips in threaded chats or people complaining about lost context, instead of only looking at the adoption numbers that look good in a launch recap." },
      { heading: "what I'd push back on", body: "Any redesign of a years old default has to deal honestly with sunk cost. A chunk of the backlash to a change like this comes from people who built workarounds for the old broken behavior and now have to unlearn them, and no amount of good design fully fixes that on its own. I'd have pushed harder for something simple right at the moment someone hits the change, explaining what's different and why, instead of relying on a help doc or a release note read days earlier. The cost of a habit change gets paid the second someone gets confused, not whenever they happen to read about it." },
      { heading: "the short version", body: "When you're changing a default in a tool people use out of habit, the rollout plan matters more than the redesign itself. Being able to go back, and explaining the change right when someone hits it, is what buys you the right to be wrong without losing trust." }
    ]
  },
  {
    slug: "basecamp-saying-no",
    tag: "saying no",
    color: "pro",
    domain: "project management / SaaS",
    title: "Basecamp's refusal to add features",
    hook: "writing down why a feature won't get built, and treating that refusal as a real product artifact.",
    sections: [
      { heading: "the problem", body: "Every mature SaaS product builds up a backlog of requests that all sound reasonable on their own. Time tracking, Gantt charts, custom fields, deeper integrations. Each one has a paying customer attached and a revenue story behind it. The actual risk isn't any single feature, it's that saying yes to enough of them turns a focused tool into something that does everything a little and nothing well." },
      { heading: "how I'd frame the bet", body: "Basecamp built a reputation on refusing this pattern, almost as part of their brand. Their founders said it directly, in blog posts, in a published book, and in years of consistent product decisions. Their position was that most feature requests are actually requests for a different product, not a missing piece of this one, and a PM's job is to tell the difference and say no to the second kind even when the customer asking is loud, paying, and right that the feature would help them personally." },
      { heading: "what they actually shipped", body: "The product stayed deliberately narrow for years compared to competitors who added Gantt charts and time tracking as default expectations. When Basecamp did eventually add time tracking, they were upfront that it wasn't a priority for them and explained their reasoning instead of quietly catching up to a feature checklist. That's the unusual part. Most companies that resist a feature do it quietly and eventually give in. Basecamp made the refusal itself part of the pitch, betting that customers who actually wanted simplicity would choose the product specifically because of what it didn't do.\n\nThe real deliverable here isn't a shipped feature, it's the public reasoning. Writing down \"here's why we won't build this, and here's what we think you should use instead\" is a real product artifact. It costs you some customers outright, the ones who genuinely needed the missing feature and left. But it sends a clear signal to everyone else about what the product is for, which avoids a worse failure mode down the line: customers who got everything they asked for and ended up with a bloated tool they no longer recognize." },
      { heading: "what I'd push back on", body: "A culture that says no this consistently risks turning into reflexive resistance instead of case by case judgment. There's a real difference between \"this request is genuinely a different product\" and \"this request is just annoying to build,\" and a strong public stance makes it easy to justify the second one as the first after the fact. I'd want the no's revisited on an actual schedule, not just defended when someone pushes back, with a standing question of whether the market has shifted enough to reopen the conversation. A no that was right in 2010 isn't automatically right forever." },
      { heading: "the short version", body: "A good no isn't a one line rejection, it's an argument good enough that the person asking understands the tradeoff even if they don't like the answer. Saying no consistently and in public is a positioning decision, not just a backlog decision." }
    ]
  },
  {
    slug: "tiktok-feed-ranking",
    tag: "AI ranking",
    color: "teal",
    domain: "social media / AI ranking",
    title: "TikTok's For You algorithm",
    hook: "the tradeoff between the signal that's cheapest to measure and the one that actually predicts whether someone's glad they watched.",
    sections: [
      { heading: "the problem", body: "A ranking algorithm for an endless scroll feed has a built in conflict. The signals that are cheapest and fastest to measure, watch time, completion rate, how fast someone opens the app again, are not the same signals that predict whether someone is actually glad they spent their evening on it. Optimizing purely for the first set is technically easy and rewarded right away. It's also the exact mechanism behind the widely reported complaint that short video feeds can pull people in well past the point they're enjoying it." },
      { heading: "how I'd frame the bet", body: "TikTok's For You feed is generally understood, through public statements, leaked internal documents, and reporting, to rank content mainly on predicted watch completion and how likely you are to rewatch it, with much less weight on who you actually follow. That's a deliberate product bet, not just a technical default. A feed driven mainly by your follow graph, closer to early Instagram or Facebook, tends to plateau once your network is established. A feed driven by interest signals can keep finding new content indefinitely because it isn't limited by who you happen to know. The tradeoff is that a system with no real input from someone's stated preferences or social ties has fewer natural brakes. There's no signal for \"I follow boring accounts on purpose to balance myself out.\"" },
      { heading: "what they actually shipped", body: "The public response to this tension has been a layer of guardrails added after the engagement first system was already working. Screen time reminders, nudges meant to break repetitive recommendation loops, and in some places restricted modes for younger users with hard limits and a curated content pool. These are worth noticing because they're not improvements to the ranking itself, they're explicit overrides sitting on top of a system the team apparently didn't trust to self correct. That's a real admission. The guardrails exist because the core thing they're optimizing for, completion and re engagement, doesn't naturally land on what's good for someone's actual wellbeing, so they patched the gap with policy instead of changing what the algorithm is actually optimizing for.\n\nThe other visible move is the periodic, public push to inject variety into recommendations on purpose, surfacing content outside someone's usual pattern, which exists specifically to counter the algorithm's own tendency to narrow someone into a tighter and tighter loop the longer they watch." },
      { heading: "what I'd push back on", body: "Bolting wellbeing guardrails onto an engagement first system after the fact is the cheaper path, but it puts the product in the position of fighting its own algorithm instead of building one that doesn't need fighting. I'd push for weighting something closer to \"are you actually glad you watched this session,\" even an imperfect version like an occasional one tap prompt at the end of a session, directly into the ranking itself instead of treating wellbeing as a separate feature bolted on the side. That's harder to measure and harder to defend internally, and it probably costs some short term watch time. But it's the difference between a product that's good for people as a side effect of policy, and one that's good for people by design." },
      { heading: "the short version", body: "When the cheapest signal to measure, watch time, isn't the signal you actually care about, user wellbeing, adding guardrails on top is a patch, not a fix. The real work is getting the harder, truer signal into the algorithm itself." }
    ]
  },
  {
    slug: "atlas-nova-instalily-demo",
    tag: "live demo",
    color: "accent",
    domain: "AI teammates / B2B onboarding",
    title: "Atlas: an onboarding teammate, built for InstaLILY",
    hook: "a working AI teammate that onboards a user step by step. built for the kind of engagement loop the InstaLILY PM role is about.",
    hasDemoIframe: true,
    demoSrc: "demos/atlas-nova-onboarding.html",
    sections: [
      { heading: "how to read this", body: "30 seconds: scroll to the demo card at the bottom and hit play. 3 minutes: read on for the how and the why." },
      { heading: "the problem", body: "Most B2B SaaS onboarding is a checklist with a video attached. That works fine when the user already knows why they signed up. It falls apart quietly everywhere else. Time to first value catches the failure, but it's almost always measured weeks after the person who bounced already forgot the product's name.\n\nThe failure mode is silent. A user who quits your setup flow doesn't file a bug, they just don't come back, and the team's default assumption is that the product wasn't a fit, when the truer story is often that the first ten minutes never actually explained what the product was for." },
      { heading: "how I'd frame the bet", body: "If the shape of the problem is a user who doesn't know what to do next, the shape of the answer isn't a better checklist. It's someone to ask. A conversational teammate can reorder around what you're trying to do, skip steps that don't apply, explain why a step exists before asking you to do it, and handle the tangent questions that would've sent someone to a help doc they were never going to open.\n\nThe tradeoff is honest. A conversation is slower than a form for someone who already knows what they want. The pattern only pays back where the cost of a quiet drop off is higher than the cost of a slower first session. That's most B2B, and specifically the wedge InstaLILY is building for." },
      { heading: "the demo", body: "Atlas is a fictional B2B SaaS product. Nova is the AI teammate that onboards a new user into it, conversationally, instead of dropping a checklist on them and walking away. While you talk to Nova, a side panel tracks what a PM would actually want to see: percent of setup complete, time to first value, exchange count, and which of the four setup steps are done. Finish all four and the loop resets, the same shape as a habit loop in a real product, not just a one time onboarding.\n\nThe conversation runs on live model calls through a Cloudflare Worker proxy, not a scripted simulation. The interesting part of conversational onboarding isn't the happy path, it's how the teammate handles the tangent, the follow up, the user who wants to skip ahead. A scripted demo would hide all of that. This one doesn't." },
      { heading: "the why", body: "InstaLILY builds AI teammates for B2B workflows, and the open PM role is split across two things: the platform layer that makes the product scale, and the engagement layer that gets users to actually form a habit with it. I didn't want to just say I understood that split in a cover letter. I wanted to hand over something built to that exact brief.\n\nAtlas is small on purpose. Four steps, one conversation, one side panel. Every piece maps to the job description: the steps to onboarding speed, the signals panel to usage data engineering and product can act on, the loop counter to habit formation, not a one time setup nobody returns to." },
      { heading: "what I'd push back on", body: "The demo runs in session, so everything Nova knows about the user resets when you close the tab. In a real product that's the whole ballgame, because the reason onboarding is expensive is that you can't just do it once. Persisting the signal panel and letting Nova pick up where a prior session left off is the version that actually earns its keep.\n\nThe four step loop is small on purpose. In a live product the setup surface would be wider and the harder question isn't sequencing, it's what to skip. The whole thing also assumes a conversation is what the user wants at that moment. Some users would rather be handed the checklist and left alone. A production version would need to notice that quickly and switch shape." }
    ]
  }
];
